version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2-node-browsers
      - image: circleci/mysql:5.7
    working_directory: ~/bbs-app
    steps:
      - checkout
      - run: sudo docker-php-ext-install pdo_mysql
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo docker-php-ext-install zip
      - run: sudo composer self-update
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "bbs-app/composer.json" }}
            - composer-v1-
      - run: ls
      - run: composer install -n --prefer-dist --working-dir=/bbs-app
      - save_cache:
          key: composer-v1-{{ checksum "bbs-app/composer.json" }}
          paths:
            - vendor
      - run: php artisan migrate
      - run: php artisan db:seed
      - run: php ./vendor/bin/phpunit

      - restore_cache:
          keys:
            - node-v1-{{ checksum "bbs-app/package-lock.json" }}
            - node-v1-
      - run: yarn install
      - save_cache:
          key: node-v1-{{ checksum "bbs-app/package-lock.json" }}
          paths:
            - node_modules
      - run: touch storage/testing.sqlite
      - run: php artisan migrate --env=testing --database=sqlite_testing --force
      - run: ./vendor/bin/codecept build
      - run: ./vendor/bin/codecept run
          