version: 2
jobs:
  one:
    docker:
      - image: circleci/php:7.2-node-browsers
    steps:
      - checkout
      - run: echo "A first hello"
      - run: mkdir -p workspace
      - run: echo "Trying out workspaces" > workspace/output
      - persist_to_workspace:
        root: workspace
        paths:
          - output
  two:
    docker:
      - image: circleci/php:7.2-node-browsers
    steps:
      - checkout
      - run: echo "A more familiar hi"
      - attach_workspace:
        at: workspace
        
      - run: |
        if [[$(ca workspace/output) == "Trying out workspaces" ]]; then
          echo "It worked!";
        else
          echo "Nope!"; exit 1
        fi
workflows:
  version: 2
    one_and_two:
      jobs:
        - one
        - two:
          requires:
            - one
